import type { Listing } from "./types";

const img = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1600&q=70`;

const exteriors = [
  img("1568605114967-8130f3a36994"),
  img("1512917774080-9991f1c4c750"),
  img("1600596542815-ffad4c1539a9"),
  img("1600585154340-be6161a56a0c"),
  img("1600607687939-ce8a6c25118c"),
  img("1580587771525-78b9dba3b914"),
  img("1570129477492-45c003edd2be"),
  img("1613977257363-707ba9348227"),
  img("1600047509807-ba8f99d2cdde"),
  img("1449844908441-8829872d2607"),
  img("1523217582562-09d0def993a6"),
  img("1605276374104-dee2a0ed3cd6"),
];

const interiors = [
  img("1560448204-e02f11c3d0e2"),
  img("1502672260266-1c1ef2d93688"),
  img("1512915922686-57c11dde9b6b"),
  img("1598228723793-52759bba239c"),
];

const land = [img("1494203484021-3c454daf695d"), img("1416331108676-a22ccb276e35")];

/**
 * Demo inventory used until a licensed MLS feed (CREA DDF or board IDX) is connected.
 * Shape matches what the real provider returns so pages do not change.
 */
const baseListings: Listing[] = [
  {
    id: "1",
    slug: "16244-92-avenue-surrey",
    mlsNumber: "R2841190",
    title: "Renovated Family Home on a Quarter Acre",
    address: "16244 92 Avenue",
    city: "Surrey",
    neighbourhood: "Fleetwood",
    province: "BC",
    postalCode: "V4N 3C4",
    price: 1698000,
    status: "new",
    category: "mls",
    propertyType: "detached",
    bedrooms: 5,
    bathrooms: 3,
    livingAreaSqFt: 2840,
    lotSizeSqFt: 10890,
    yearBuilt: 1992,
    description:
      "Fully updated five bedroom home on a flat 10,890 sq ft lot in the heart of Fleetwood. New kitchen, new roof and a two bedroom mortgage helper with a separate entrance. Walking distance to Fleetwood Park Secondary and the future SkyTrain extension along Fraser Highway.",
    highlights: [
      "Two bedroom legal suite",
      "Future SkyTrain corridor",
      "Flat, fully fenced lot",
      "Detached shop / RV parking",
    ],
    images: [exteriors[0], interiors[0], interiors[1], exteriors[1]],
    listedAt: "2026-07-18",
  },
  {
    id: "2",
    slug: "2208-1188-pinetree-way-coquitlam",
    mlsNumber: "R2839014",
    title: "Sub-Penthouse with Mountain and City Views",
    address: "2208 - 1188 Pinetree Way",
    city: "Coquitlam",
    neighbourhood: "Coquitlam Town Centre",
    province: "BC",
    postalCode: "V3B 0T4",
    price: 879000,
    status: "active",
    category: "mls",
    propertyType: "condo",
    bedrooms: 2,
    bathrooms: 2,
    livingAreaSqFt: 954,
    yearBuilt: 2019,
    description:
      "Corner two bedroom plus den on the 22nd floor with unobstructed north-facing mountain views. Steps to Lincoln SkyTrain, Lafarge Lake and Coquitlam Centre. Excellent rental performer for investors.",
    highlights: ["Two parking stalls", "Rentals allowed", "Steps to SkyTrain", "Air conditioning"],
    images: [exteriors[2], interiors[2], interiors[3]],
    listedAt: "2026-07-09",
  },
  {
    id: "3",
    slug: "8721-152-street-surrey-land-assembly",
    mlsNumber: "R2830771",
    title: "Land Assembly Site — 1.4 Acres, Townhouse Designation",
    address: "8721 152 Street",
    city: "Surrey",
    neighbourhood: "Fleetwood",
    province: "BC",
    price: 4250000,
    status: "active",
    category: "mls",
    propertyType: "land",
    bedrooms: 0,
    bathrooms: 0,
    livingAreaSqFt: 0,
    lotSizeSqFt: 60984,
    description:
      "Part of a three property assembly totalling 1.4 acres, designated for townhouse density in the Fleetwood Plan. Holding income in place while the application proceeds. Full package including servicing and density analysis available to qualified developers.",
    highlights: [
      "Townhouse designation",
      "Holding income in place",
      "Assembly package available",
      "Pre-application meeting completed",
    ],
    images: [land[0], land[1]],
    listedAt: "2026-06-28",
  },
  {
    id: "4",
    slug: "13455-232-street-maple-ridge",
    mlsNumber: "R2843002",
    title: "Brand New Build with Legal Suite and Coach House",
    address: "13455 232 Street",
    city: "Maple Ridge",
    neighbourhood: "Silver Valley",
    province: "BC",
    price: 1949000,
    status: "new",
    category: "mls",
    propertyType: "new-construction",
    bedrooms: 7,
    bathrooms: 6,
    livingAreaSqFt: 4120,
    lotSizeSqFt: 7200,
    yearBuilt: 2026,
    description:
      "Builder's own home, completed this spring. Main residence with four bedrooms up, a two bedroom legal suite and a detached coach house — over $90,000 in projected annual rental income. 2-5-10 warranty in place.",
    highlights: [
      "2-5-10 new home warranty",
      "Legal suite plus coach house",
      "Radiant heat and A/C",
      "Built by Spot Group",
    ],
    images: [exteriors[3], interiors[0], exteriors[4]],
    listedAt: "2026-07-21",
  },
  {
    id: "5",
    slug: "45-19560-68-avenue-langley",
    mlsNumber: "R2836540",
    title: "End Unit Townhome Backing Greenbelt",
    address: "45 - 19560 68 Avenue",
    city: "Langley",
    neighbourhood: "Clayton",
    province: "BC",
    price: 949900,
    status: "active",
    category: "mls",
    propertyType: "attached",
    bedrooms: 3,
    bathrooms: 3,
    livingAreaSqFt: 1610,
    yearBuilt: 2014,
    description:
      "Bright end unit with a double side-by-side garage and a fenced yard backing onto protected greenbelt. Low strata fees, pets and rentals allowed, minutes to Willowbrook and Highway 1.",
    highlights: ["End unit", "Double garage", "Greenbelt exposure", "Pet friendly strata"],
    images: [exteriors[5], interiors[1], interiors[2]],
    listedAt: "2026-07-02",
  },
  {
    id: "6",
    slug: "3390-e-27th-avenue-vancouver",
    mlsNumber: "R2828991",
    title: "Character Home on a 33 x 122 RS-1 Lot",
    address: "3390 E 27th Avenue",
    city: "Vancouver",
    neighbourhood: "Renfrew Heights",
    province: "BC",
    price: 1875000,
    status: "active",
    category: "mls",
    propertyType: "detached",
    bedrooms: 4,
    bathrooms: 2,
    livingAreaSqFt: 2100,
    lotSizeSqFt: 4026,
    yearBuilt: 1948,
    description:
      "Solid character home held by the same family for 30 years. Live in, rent out or build up to a multiplex under the new City of Vancouver zoning. Preliminary multiplex massing study available.",
    highlights: [
      "Multiplex potential",
      "Lane access",
      "Massing study available",
      "Quiet tree-lined street",
    ],
    images: [exteriors[6], interiors[3]],
    listedAt: "2026-06-24",
  },
  {
    id: "7",
    slug: "7188-138-street-surrey-off-market",
    mlsNumber: null,
    title: "Off-Market Fixer — Estate Sale, Sold As-Is",
    address: "7188 138 Street",
    city: "Surrey",
    neighbourhood: "East Newton",
    province: "BC",
    price: 1125000,
    status: "active",
    category: "exclusive",
    propertyType: "detached",
    bedrooms: 4,
    bathrooms: 2,
    livingAreaSqFt: 2260,
    lotSizeSqFt: 7841,
    yearBuilt: 1978,
    description:
      "Estate sale being sold strictly as-is, where-is. Needs a full renovation — roof, kitchen, baths and mechanical. Numbers pencil for a flip or a hold with a suite. Not on MLS; contact for the full package and access.",
    highlights: [
      "Never listed on MLS",
      "Sold as-is, where-is",
      "Flexible completion",
      "Renovation scope available",
    ],
    images: [exteriors[7], exteriors[8]],
    listedAt: "2026-07-14",
  },
  {
    id: "8",
    slug: "10422-city-parkway-surrey-exclusive",
    mlsNumber: null,
    title: "Exclusive: 8-Unit Rental Building, Fully Tenanted",
    address: "10422 City Parkway",
    city: "Surrey",
    neighbourhood: "Whalley",
    province: "BC",
    price: 3390000,
    status: "active",
    category: "exclusive",
    propertyType: "multifamily",
    bedrooms: 12,
    bathrooms: 8,
    livingAreaSqFt: 6800,
    lotSizeSqFt: 8100,
    yearBuilt: 1994,
    description:
      "Eight suite rental building two blocks from Surrey Central SkyTrain, offered exclusively to qualified investors. Rents approximately 20% under market with turnover upside. Rent roll and expense statements provided after NDA.",
    highlights: [
      "5.1% cap on current rents",
      "Under-market rents",
      "Transit-oriented area plan",
      "Rent roll after NDA",
    ],
    images: [exteriors[9], exteriors[10]],
    listedAt: "2026-07-05",
  },
  {
    id: "9",
    slug: "2680-mccallum-road-abbotsford-exclusive",
    mlsNumber: null,
    title: "Exclusive: Duplex Lot Package, Permits Ready",
    address: "2680 McCallum Road",
    city: "Abbotsford",
    neighbourhood: "Central Abbotsford",
    province: "BC",
    price: 799000,
    status: "coming-soon",
    category: "exclusive",
    propertyType: "land",
    bedrooms: 0,
    bathrooms: 0,
    livingAreaSqFt: 0,
    lotSizeSqFt: 8712,
    description:
      "Serviced duplex lot with building permits ready to issue. Ideal for a small builder wanting to start immediately. Plans, permits and a fixed-price construction budget included in the package.",
    highlights: ["Permits ready to issue", "Plans included", "Fixed-price build budget", "Off-market"],
    images: [land[1], exteriors[11]],
    listedAt: "2026-07-22",
  },
  {
    id: "10",
    slug: "6055-fraser-street-vancouver",
    mlsNumber: "R2822104",
    title: "Two Bedroom Investor Condo Near Fraser Street",
    address: "305 - 6055 Fraser Street",
    city: "Vancouver",
    neighbourhood: "Sunset",
    province: "BC",
    price: 719000,
    status: "sold",
    category: "mls",
    propertyType: "condo",
    bedrooms: 2,
    bathrooms: 2,
    livingAreaSqFt: 820,
    yearBuilt: 2017,
    description:
      "Sold in six days with multiple offers. Two bedroom corner unit purchased by an investor client at a 4.2% cap rate on day one rents.",
    highlights: ["Sold over asking", "Six days on market", "Investor purchase"],
    images: [exteriors[1], interiors[2]],
    listedAt: "2026-05-11",
  },
  {
    id: "11",
    slug: "8020-172-street-surrey-new-construction",
    mlsNumber: "R2842277",
    title: "Presale: 6 Unit Townhome Project, Two Homes Remaining",
    address: "8020 172 Street",
    city: "Surrey",
    neighbourhood: "Fleetwood",
    province: "BC",
    price: 1129000,
    status: "new",
    category: "mls",
    propertyType: "new-construction",
    bedrooms: 4,
    bathrooms: 4,
    livingAreaSqFt: 1980,
    yearBuilt: 2026,
    description:
      "Two remaining homes in a six unit boutique townhome project completing this fall. Side-by-side double garages, flex bedroom on the ground floor and full 2-5-10 warranty. Deposit structure available for investors.",
    highlights: ["Completing fall 2026", "2-5-10 warranty", "Assignable deposits", "Boutique project"],
    images: [exteriors[4], interiors[0], interiors[3]],
    listedAt: "2026-07-24",
  },
  {
    id: "12",
    slug: "22415-old-yale-road-langley",
    mlsNumber: "R2840550",
    title: "Rancher on Half an Acre with Development Upside",
    address: "22415 Old Yale Road",
    city: "Langley",
    neighbourhood: "Murrayville",
    province: "BC",
    price: 1599000,
    status: "active",
    category: "mls",
    propertyType: "detached",
    bedrooms: 3,
    bathrooms: 2,
    livingAreaSqFt: 1740,
    lotSizeSqFt: 21780,
    yearBuilt: 1968,
    description:
      "Clean, liveable rancher on half an acre inside the Murrayville plan area. Hold and rent while future density is confirmed, or renovate and enjoy the park-like yard.",
    highlights: ["Half acre", "Holding income", "Plan area upside", "Rancher layout"],
    images: [exteriors[11], interiors[1]],
    listedAt: "2026-07-12",
  },
];

/** Per-listing extras layered onto the base records above. */
const extras: Record<
  string,
  {
    featured?: boolean;
    features?: string[];
    latitude?: number;
    longitude?: number;
    openHouses?: Listing["openHouses"];
  }
> = {
  "16244-92-avenue-surrey": {
    featured: true,
    latitude: 49.1704,
    longitude: -122.7773,
    features: [
      "Two bedroom legal suite with separate entrance",
      "Quartz kitchen with gas range",
      "New roof, furnace and hot water on demand",
      "Detached 24 x 26 shop with 200 amp service",
      "RV parking and double gate access",
      "Fully fenced, irrigated yard",
    ],
    openHouses: [
      { date: "2026-08-01", start: "1:00 PM", end: "3:00 PM" },
      { date: "2026-08-02", start: "2:00 PM", end: "4:00 PM" },
    ],
  },
  "2208-1188-pinetree-way-coquitlam": {
    featured: true,
    latitude: 49.2794,
    longitude: -122.7932,
    features: [
      "Corner plan with wraparound glass",
      "Air conditioning throughout",
      "Two side-by-side parking stalls",
      "Concierge, gym and lounge",
      "Rentals and pets permitted",
    ],
    openHouses: [{ date: "2026-08-02", start: "12:00 PM", end: "2:00 PM" }],
  },
  "8721-152-street-surrey-land-assembly": {
    featured: true,
    latitude: 49.1602,
    longitude: -122.8014,
    features: [
      "1.4 acre three-property assembly",
      "Townhouse designation in the Fleetwood Plan",
      "Servicing and density analysis complete",
      "Existing homes provide holding income",
    ],
  },
  "13455-232-street-maple-ridge": {
    featured: true,
    latitude: 49.2361,
    longitude: -122.5457,
    features: [
      "Two bedroom legal suite plus detached coach house",
      "Radiant in-floor heat with central air",
      "Oversized triple garage",
      "2-5-10 new home warranty",
      "Built by SPOT Group",
    ],
    openHouses: [{ date: "2026-08-01", start: "11:00 AM", end: "1:00 PM" }],
  },
  "45-19560-68-avenue-langley": {
    latitude: 49.1362,
    longitude: -122.6934,
    features: [
      "End unit with extra windows",
      "Double side-by-side garage",
      "Fenced yard backing greenbelt",
      "Low monthly strata fee",
    ],
  },
  "3390-e-27th-avenue-vancouver": {
    featured: true,
    latitude: 49.2469,
    longitude: -123.0357,
    features: [
      "33 x 122 lot with lane access",
      "Preliminary multiplex massing study",
      "Original oak floors and coved ceilings",
      "Separate basement entrance",
    ],
  },
  "7188-138-street-surrey-off-market": {
    latitude: 49.1305,
    longitude: -122.8484,
    features: [
      "Sold strictly as-is, where-is",
      "7,841 sq ft lot",
      "Renovation scope and budget available",
      "Flexible completion for cash buyers",
    ],
  },
  "10422-city-parkway-surrey-exclusive": {
    featured: true,
    latitude: 49.1889,
    longitude: -122.8489,
    features: [
      "Eight self-contained suites",
      "Two blocks to Surrey Central SkyTrain",
      "Rents roughly 20% under market",
      "Rent roll and expenses released after NDA",
    ],
  },
  "2680-mccallum-road-abbotsford-exclusive": {
    latitude: 49.0431,
    longitude: -122.3079,
    features: [
      "Building permits ready to issue",
      "Duplex plans included",
      "Fixed-price construction budget",
      "Fully serviced lot",
    ],
  },
  "6055-fraser-street-vancouver": {
    latitude: 49.2262,
    longitude: -123.0906,
    features: ["Corner plan", "Two parking stalls", "Rentals allowed"],
  },
  "8020-172-street-surrey-new-construction": {
    featured: true,
    latitude: 49.1596,
    longitude: -122.7405,
    features: [
      "Two of six homes remaining",
      "Side-by-side double garage",
      "Ground floor flex bedroom",
      "2-5-10 warranty, assignable deposits",
    ],
    openHouses: [{ date: "2026-08-03", start: "1:00 PM", end: "4:00 PM" }],
  },
  "22415-old-yale-road-langley": {
    latitude: 49.0925,
    longitude: -122.6293,
    features: [
      "21,780 sq ft park-like lot",
      "Single level rancher layout",
      "Inside the Murrayville plan area",
      "Detached workshop",
    ],
  },
};

const citySlug = (city: string) => city.toLowerCase().replace(/\s+/g, "-");

/**
 * Demo inventory shown until a licensed MLS® feed (CREA DDF or board IDX) is
 * connected. Every surface that renders these records labels them as
 * demonstration data.
 */
export const demoListings: Listing[] = baseListings.map((listing) => ({
  ...listing,
  communitySlug: citySlug(listing.city),
  ...extras[listing.slug],
}));
